[package]
name = "fanshim"
version = "0.1.0"
authors = ["Joao Moreno <mail@joaomoreno.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
tokio = "0.1"

[dependencies.sysfs_gpio]
version = "0.5"
default-features = false
features = ["use_tokio"]

[profile.release]
codegen-units=1